[package]
name = "bufdraw"
version = "0.1.4"
authors = ["Ilya Sheprut <optozorax@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/optozorax/bufdraw"
description = """
Cross-platform window context and rendering library in buffer.
"""

[dependencies]
miniquad = "0.2.9"