#!/bin/bash

cp -R www www_$1
cargo build --target wasm32-unknown-unknown --release --example $2
cp target/wasm32-unknown-unknown/release/examples/$2.wasm ../bufdraw/www_$1/target.wasm
wasm-strip www_$1/target.wasm

git checkout gh-pages
git add www_$1 www_$1/target.wasm --force
git commit -m "add \"$2\" example version \"$1\" to gh-pages"
git push
git checkout master